# Generated by Django 4.1 on 2022-08-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_peso_producto_precio'),
        ('venta', '0002_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='producto.producto'),
        ),
    ]
