# Generated by Django 4.1 on 2022-08-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_venta_id_producto_venta_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='producto',
            new_name='producto_id',
        ),
    ]
