# Generated by Django 4.0.3 on 2022-09-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_rename_producto_id_venta_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
