# Generated by Django 4.1 on 2022-09-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_venta_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='producto',
            new_name='producto_id',
        ),
    ]
