# Generated by Django 4.1 on 2022-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
