# Generated by Django 4.0.3 on 2022-10-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
