# Generated by Django 4.0.3 on 2022-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_venta_cliente_descripcion_venta_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(max_length=20),
        ),
    ]
