# Generated by Django 4.1 on 2022-10-15 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('venta', '0014_alter_venta_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente_descripcion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_telefono',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
    ]
