# Generated by Django 4.0.3 on 2022-10-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('venta', '0015_remove_venta_cliente_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ManyToManyField(blank=True, null=True, to='cliente.cliente'),
        ),
    ]
