# Generated by Django 4.0.3 on 2022-10-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('venta', '0018_remove_venta_cliente_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ManyToManyField(to='cliente.cliente'),
        ),
    ]
