# Generated by Django 4.0.3 on 2022-10-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('venta', '0023_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='cliente.cliente'),
        ),
    ]
