# Generated by Django 4.0.3 on 2022-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0024_alter_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='productoManual',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
