# Generated by Django 4.0.3 on 2022-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0025_venta_productomanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='productoManual',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
