# Generated by Django 4.0.3 on 2022-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('venta', '0027_remove_venta_cliente_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='cliente.cliente'),
        ),
    ]
