# Generated by Django 4.0.3 on 2022-12-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0034_alter_venta_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='productoManual',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
