# Generated by Django 4.0.3 on 2022-12-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_peso_producto_precio'),
        ('venta', '0036_alter_venta_productomanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='productoManual',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
