# Generated by Django 4.0.3 on 2023-04-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0041_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.CharField(max_length=15),
        ),
    ]
