# Generated by Django 4.0.3 on 2023-05-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
    ]
